services:
  mongo:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ""
      ME_CONFIG_BASICAUTH_PASSWORD: ""
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo

  api:
    build: ./apps/api
    container_name: api
    restart: always
    ports:
      - 4000:4000
    environment:
      APP_PORT: 4000
      APP_ENV: prod
      APP_DEBUG: true
      MONGO_URI: mongodb://admin:pass@mongo:27017
      MONGO_DB: bookshelf
    depends_on:
      - mongo

  web:
    build: ./apps/web
    container_name: web
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  data:
